### ISSUE TITLE
Crash when turning mobile data on/off [bug]

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#67]
When I turn my mobile data off (and maybe even when wifi gets turned off, need to double test this one) I get a crash out of LC

```
06-29 08:49:11.180 5626-5626/tv.piratemedia.lightcontroler I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
06-29 08:49:11.287 5626-5626/tv.piratemedia.lightcontroler D/AndroidRuntime: Shutting down VM
06-29 08:49:11.296 5626-5626/tv.piratemedia.lightcontroler E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: tv.piratemedia.lightcontroler, PID: 5626
                                                                             java.lang.RuntimeException: Unable to start receiver tv.piratemedia.lightcontroler.wear.wifiConnectionListener: java.lang.IllegalStateException: System services not available to Activities before onCreate()
                                                                                 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.IllegalStateException: System services not available to Activities before onCreate()
                                                                                 at android.app.Activity.getSystemService(Activity.java:5266)
                                                                                 at tv.piratemedia.lightcontroler.utils.getWifiName(utils.java:85)
                                                                                 at tv.piratemedia.lightcontroler.wear.wifiConnectionListener.onReceive(wifiConnectionListener.java:43)
                                                                                 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725)
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

I tested on my master before this  commit: https://github.com/eliotstocker/Light-Controller/commit/880f844e6c8984b7613a09e3bf8b7c3ed9395c58 and all worked fine, then pulled upstream and now I get this crash. I _assume_ related to this commit where you tried to fix this issue? https://github.com/eliotstocker/Light-Controller/commit/69dfcb9ee4b2f33a44db2ad6cd1f30ac5ccf16e5 (but it was never an issue for me before this)

**Comment by mrwhale** [comment]
So i "Fixed" this by rolling back one of your commits (69dfcb9) and included this change in the "Better Pebble" PR (https://github.com/mrwhale/Light-Controller/commit/89b970ddb5b4102fab7b11ade8a2c6beca6d0106)

Obviously it affects whatever bug you were trying to initially fix

**Comment by eliotstocker** [comment]
yeah, ill fix the main bug better (only seems to affect samsung devices)
